os:
  - linux
language: nix
sudo: required
git:
  depth: 1
  submodules: false
before_script:
  - sudo mkdir -p /etc/nix
  - echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
script:
  - |
    nix-env -iA shellcheck -f '<nixpkgs>'
    # for some reason, `find` with multiple search paths piped to xargs
    # produces no output
    find lib -type f -print | xargs shellcheck -x
    find scripts -type f -print | xargs shellcheck -x
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - |
    cachix use dapp
    nix-env -iA dapp -f https://github.com/dapphub/dapptools/archive/nohup.tar.gz
    git clone https://github.com/dapphub/dapptools --branch nohup ~/.dapp/dapptools
    dapp testnet &
  - cachix use tdds
  - cachix push tdds --watch-store &
  - nix-build -j2 | cachix push tdds
  - nix-shell --run "deploy-testchain.sh && scripts/auth-checker"
